- src/components/terminals/IosTerminal/IosTerminal.js
- src/pages/Home/Home.js
- src/pages/Home/Home.scss
Adds a `bodyClass` prop to `IosTerminal`.
> Adds more content to terminal examples on home page

- src/Router/Router.js
> Adding redirects for /community and /news

- src/Router/Router.js
> Redirect /docs/tables to /schema

- README.md
- src/components/Button/Button.scss
- src/components/EventList/EventList.js
- src/components/EventList/EventList.scss
- src/components/EventList/index.js
- src/components/EventListing/EventListing.js
- src/components/EventListing/EventListing.scss
- src/components/EventListing/index.js
- src/components/Pill/Pill.scss
- src/components/Tab/Tab.scss
- src/components/text/Paragraph/Paragraph.js
- src/components/text/Paragraph/Paragraph.scss
- src/data/community_events/manifest.js
- src/data/community_events/querycon18.json
- src/data/pages/home.json
- src/pages/Home/Home.js
- src/pages/Home/Home.scss
- src/styles/variables.scss
- stories/index.js
- Adds a Community Events section to the home page
- Fixes Storybook: this was broken after reorganizing the package data
- Adds transition effects to hover on Button, Tab, and Pill components
> Community events

- src/components/EventListing/EventListing.scss
> Left-align event listings on mobile

- src/data/pages/home.json
This PR adds some text that was missing to the main page under the open-source header.
> Fix text in third column of things you should know

- src/pages/BlogIndex/BlogIndex.scss
> Center the blog toggle buttons

- src/data/blog/posts/community_articles/2018-03-13-optimizing-queries.md
This is a blog post that we wrote based on our experiences from building on top of OSQuery. One of the biggest challenges was the ability to control the data properly. Much of the information was difficult to track down so we thought this might be helpful to others.
> 2018-03-13-optimizing-queries.md

- src/data/osquery_schema_versions/2.10.0.json
- src/data/osquery_schema_versions/2.10.2.json
- src/data/osquery_schema_versions/2.11.0.json
- src/data/osquery_schema_versions/2.11.2.json
- src/data/osquery_schema_versions/2.8.0.json
- src/data/osquery_schema_versions/2.9.0.json
Updating the schema JSON based on the changes in https://github.com/facebook/osquery/pull/4248.
Working towards #29
> Update table documentation data

- package.json
- src/components/BlogPost/BlogPost.scss
- src/components/Button/Button.scss
- src/pages/BlogIndex/BlogIndex.js
- src/pages/BlogIndex/BlogIndex.scss
- yarn.lock
This PR fixes #30 by truncating blog posts on the index view so you can see more!
Here is a screenshot...
> Truncate blog posts

- package.json
- src/components/OsqueryTable/OsqueryTable.js
- src/components/OsqueryTable/OsqueryTable.scss
- src/components/SchemaTOC/SchemaTOC.js
- src/components/SchemaTOC/TOCEntry/TOCEntry.js
- src/components/SchemaTOC/TOCEntry/TOCEntry.scss
- src/components/forms/fields/PlatformDropdown/PlatformDropdown.scss
- src/pages/Schema/Schema.js
- yarn.lock
If a table has been added since the prior schema version, we will see an indicator (blue pill) on the table listing as well as the table of contents entry.
> Add new indicator to schema tables

- src/pages/Schema/Schema.js
Added support so that the user can route to `current` version and added additional support to route to a specific table.
Examples:
https://osquery.io/schemas/current - will route to the `current` version of the schema
https://osquery.io/schemas/current/#asl - will route to the asl table in the `current` version of the schema
This is a pre-requisite for updating the docs with proper links.
> Fix for issue #51

- src/components/Icon/Icon.js
- src/components/Icon/svg/Calendars.svg.js
- src/components/OsqueryTable/OsqueryTable.js
- src/components/OsqueryTable/OsqueryTable.scss
> Add icon to evented tables

- src/pages/Schema/Schema.js
`scrollY` position was not set correctly. This will fix #75.
> Fix TOC position when scrolling

- src/data/pages/home.json
https://github.com/facebook/osquery/issues/4536
> address https://github.com/facebook/osquery/issues/4536

- src/data/osquery_package_versions/3.3.0.json
> bug: fixing schema for versions

- src/data/blog/posts/community_articles/2018-08-20-osquery_windows_process_auditing.md
Please see attached blog post for the "community articles".
Let me know if you have any feedback or suggestions for changes.
Thanks,
Dennis
> Adding blog post to enable event-based queries in Windows using event log.

- src/data/blog/posts/community_articles/2018-08-20-osquery_windows_process_auditing.md
Added blog post with YAML headers, tested locally.
> Added blog post with YAML headers, tested locally.

- src/data/featured_projects.json
- Windmill appears to be deleted
- Update star counts so that rankings are more accurate if error occurs during
update
> Update featured project star counts and swap SGT for Windmill

- src/data/community_events/altseccon19.json
- src/data/community_events/manifest.js
Adding live osquery event: AltSecCon 2019
> Adding Event: AtlSecCon

- src/data/community_events/hackmiami19.json
- src/data/community_events/manifest.js
- src/data/community_events/uptycs-free-osquery-workshop.json
Reverts osquery/osquery-site#120 since this caused the build to fail.
> Revert "Added two live events: HackMiami19 + Uptycs Free Osquery Workshop"

- Dockerfile
- package.json
- yarn.lock
Braces should be updated to a new version for security reasons.
> Update braces dep

- Dockerfile
- package.json
- yarn.lock
Reverts osquery/osquery-site#126 . Reverting since #125 #126 and @127 were made dependent on each other and therefore merging this one first made the others have conflicts. Will revert this first and land later again.
> Revert "Update braces dep"

- Dockerfile
- package.json
- yarn.lock
Reverts osquery/osquery-site#125
> Revert "Force insecure dependencies to secure versions"

- Dockerfile
- package.json
- yarn.lock
All critical vulns from "yarn audit" are fixed in this branch.
> Mega update of critical deps.

- src/pages/Home/Home.scss
I broke the homepage marquee in #132. This restores the feature.
> bug: Fix marquee CSS

- README.md
I didn't see this elsewhere, so I added one
> Add a note about how to deploy the site

- src/data/community_events/manifest.js
- src/data/community_events/osquery@scale.json
Adding future in person event to community events section of osquery site
> Adding future in person event to community events section of osquery site

- src/data/community_events/bsidesslc20.json
- src/data/community_events/manifest.js
I am submitting a a new  in-person Community Event PR to the osquery.io site. (BSides SLC)
> Submitting New Community Event (BSides SLC)

- src/Router/Router.js
> Allow linking to schema tables without osquery version

- src/data/osquery_package_versions/4.3.0.json
> Update windows hash 4.3.0

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Update docs to reference foundation links, and not older facebook things
> Update docs to foundation

- src/index.scss
This reverts commit eaa36e5f0e8175483170f9edf01c06a08f83b802.
> Revert "Schema page: block scroll on sidebar hover without hiding"

- src/components/Footer/Footer.js
Hack at javascript until I can get a basic sponsor shoutout in the footer. What do y'all think?
Relates To: https://github.com/osquery/foundation/issues/76
> Sponsor shoutouts

- src/components/Footer/Footer.js
AWS has been helping get the arm64 CI up and running. Let's add them to the shoutouts
> Add AWS to the sponsors list

- src/data/featured_projects.json
- Add trailofbits/osquery-extensions.
- Remove airbnb/streamalert.
- Update star counts and reorder.
> Update featured projects

- src/pages/Downloads/Downloads.js
> Remove FreeBSD header

- config/webpackDevServer.config.js
- public/_headers
- src/index.js
- yarn.lock
This will hopefully fix the issue of the website showing an empty white
screen until a hard refresh is performed after an update is deployed.
webpack-dev-server is updated to fix the local build.
> Disable service worker

- src/data/osquery_package_versions/5.5.1.json
- src/data/osquery_schema_versions/5.5.1.json
> Add missed files

- src/components/Footer/Footer.js
As agreed upon in office hours.
> Add Fleet to list of sponsors

- src/data/pages/downloads.json
> docs: Update instructions for apt-key deprecation

- .github/workflows/release.yml
Opens a PR! https://github.com/osquery/osquery-site/pull/282
Probably gets weird if it's run on a branch that exists. TBD!
> GHA driven website updates

- .github/workflows/ci.yml
- .github/workflows/deploy-to-pages.yml
- .github/workflows/release-pr.yml
- README.md
1. Update readme with current notes
2. Change branches
> Small Update

- .github/workflows/ci.yml
- .github/workflows/deploy-to-pages.yml
- Dockerfile
- package.json
- yarn.lock
Something in merging PRs broke, so I updated to node 18 and hade claude.ai fix it.
> Update to node 18
