osquery/osquery-site

src/components/forms/fields/Dropdown/Dropdown.scss, src/components/forms/fields/PlatformDropdown/PlatformDropdown.scss
* Remove box-shadow that's only visible on firefox
* Remove background-color from text that makes platform version look
strange
Before:
After:
=> CSS tweaks to make Firefox look like Chrome

src/components/SchemaTOC/SchemaTOC.js, src/index.css, src/index.scss, src/pages/Schema/Schema.js
This prevents the "scroll chaining" behavior when scrolling content
which scrolls outer content once the inner content can no longer be
scrolled. This was causing issues with the schema pages sidebar since
scroll to the top would scroll `body` and immediately update the sidebar
scroll.
This resolves the issue by setting `overflow: hidden;` on `body` when
the users mouse enters the sidebar and removes it when the mouse leaves.
Because body is unscrollable the scroll chaining "stops" at the sidebar.
=> Prevent sidebar scroll chaining

src/components/Footer/Footer.js, src/pages/Home/Home.js, stories/index.js
Hi! The new website is gorgeous! I noticed that GitHub was spelled with a lowercase `h` is a few places; fix attached for your consideration 🤘
=> Give GitHub an uppercase H

src/data/osquery_package_versions/2.11.2.json, src/data/osquery_schema_versions/2.11.2.json
It looks like we over-wrote the 2.11.2 schema data with the updated 2.11.2 package data in commit cd51799. We're reverting that commit and creating a new commit that updates the 2.11.2 package data w/ the Windows package.
=> Package 2.11.2 fix

src/pages/Downloads/Downloads.js
IE and Safari <= 10.1 [don't support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values) `Object.values`. Replacing with lodash method. `Object.keys` is more widely accepted; using lodash for that method only for consistency.
=> Use lodash methods for values and keys

src/data/pages/home.json
Noticed a small omission error in the copy of the `Osquery Events` section, this PR corrects that sentence.
=> Minor tweak to Osquery Events copy.

public/_headers
https://github.com/facebook/create-react-app/issues/2440
This should resolve an issue where `index.html` is cached and pointing
at an invalid JavaScript bundle.
=> Don't cache service worker file

src/components/terminals/TerminalBody/TerminalBody.js
Removes the `$ ` leader at the beginning of each line when copying and pasting.
close #50
=> Copy and paste from Terminal body removes leader

src/components/terminals/TerminalBody/TerminalBody.js
Replaces the "lookbehind" regex feature with a less-elegant split/join solution.
=> Update regex scheme for removing leader

package.json
There's a bug w/ node-sass which requires us to rebuild it on each install.
=> Add script to rebuild node-sass on postinstall step

src/pages/Home/Home.scss
The large circle call to action links for additional resources (slack, docs, github) on the home page were extending past the viewport width on smaller widths. This caused a horizontal scroll. This commit switches the links to column view before causing the scroll.
Resolves #57
=> Break to column view earlier in resources section

src/components/BlogPost/BlogPost.scss, src/pages/BlogShow/BlogShow.scss
Sets a max width on images so that they shrink to fit on mobile. Refactors CSS into a better place.
Also brings font size down to 16px at smaller resolutions, and fixes formatting of ordered lists.
=> Blog post: fix images in mobile view

src/pages/Schema/Schema.js
`global.window.scrollY` position was not being maintained.
=> Fixed bug #80

src/pages/Schema/Schema.js
Simplifies the logic for the sticky TOC: if the header is visible, set the TOC to static. If the header isn't visible, fix the TOC to the upper corner.
Fixes #69
=> Fix issue in which header would sometimes overlap TOC

src/data/osquery_package_versions/3.2.6.json
Fix for https://github.com/osquery/osquery-site/issues/86
Tested updated url works that and filename is correct
=> Updated linux 3.2.6 file name and url

src/components/DownloadCard/DownloadCard.js, src/data/osquery_package_versions/2.10.0.json, src/data/osquery_package_versions/2.10.2.json, src/data/osquery_package_versions/2.11.0.json, src/data/osquery_package_versions/2.11.2.json, src/data/osquery_package_versions/2.7.0.json, src/data/osquery_package_versions/2.8.0.json, src/data/osquery_package_versions/2.9.0.json, src/data/osquery_package_versions/3.2.4.json, src/data/osquery_package_versions/3.2.6.json, src/pages/Downloads/Downloads.js, stories/index.js
This PR resolves the issue of a bad download links on 3.2.6 and potentially other versions. 
It also removes the explicit download links in favor of an implicitly built link.
This will reduce the number of places that a human must copy and paste these versions and filenames and the URLS will then be built at render.
This does duplicate the resolution provided in #87 - sorry about that! 
Closes #86
=> Update version JSON to build implicit download URL to reduce human copy/paste errors

src/pages/Schema/Schema.js
Ensure scroll handlers are in place prior to loading the tableName prop from the router.
=> Fix for #90

public/index.html, src/index.js
We now import the CSS resources locally, as opposed to via CDN. This resolves  https://github.com/osquery/osquery-site/issues/96
Before:
After:
=> Changed how we import react-select styles to fix #96.

CODE_OF_CONDUCT.md, LICENSE-DOCUMENTATION, README.md
This diff would license the content of the repository under the Creative Commons Documentation License, https://creativecommons.org/licenses/by/4.0/. We also add a code of conduct which is Facebook's standard code of conduct.
=> License under Creative Commons Documentation, add code of conduct

Dockerfile, package.json, yarn.lock
Use yarn's resolutions (https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md)
to force the various versions of insecure packages to the most recent version:
fstream, sshpk, clean-css, handlebars, js-yaml are all pinned via "resolutions" for now..
Push axios to  0.19.0 via package.json
While here pin the version of nodejs to 10 for our Docker images
otherwise we get compilation problems when running "make all"
as some of the deps are incompatible with latest version of node.
While here sync eslint between regular and devDepends + yarn upgrade
yarn was giving a warning:
warning package.json: "dependencies" has dependency "eslint" with range "4.10.0" that collides with a dependency in "devDependencies" of the same name with version "4.11.0"
This …
=> Force insecure dependencies to secure versions

Dockerfile, package.json, yarn.lock
Update a large number of site dependencies to versions that are safer.
**_Note: requires node version 10._**
Please ensure the droplet where this runs is pinned to node 10.  (newer than 10 seems to break and will require larger refactor of deps, older than 10 seems to cause problems with storybook deps).
=> Mega update deps

package.json
Copy the index page to the 404 page so that the JS can attempt to load the URL.
Closes #138
=> Fix 404 on gh-pages when using non-homepage URL

package.json, src/helpers/get_github_repo.js, src/pages/Home/Home.js, yarn.lock
Removes this large dependency that was only used in a single place. The
browser-native APIs provide a suitable replacement. This significantly
reduces the size of the compiled bundle, but has no significant change
after minimization and gzipping.
=> Remove axios dependency

package.json, yarn.lock
We are not likely to be effected by the vulnerabilities, but upgrading
just to be safe.
Upgrade Babel and Jest to get new versions of the handlebars and lodash
dependencies not effected by the prototype pollution vulnerabilities.
=> Update dependencies for security alerts

src/data/osquery_package_versions/4.0.1.json
Looks like the generator script is out of date. Manually fix the links
This will need to be fixed in the new_release script as well.
Thanks @terracatta
=> Fix download links

src/data/osquery_schema_versions/4.0.1.json, src/data/osquery_schema_versions/4.0.2.json
This adds missing paths to the table URLs in schemas of 4.0.1 and 4.0.2.
=> Fix broken table URLs in schemas

src/data/osquery_package_versions/4.1.2.json
I rebuilt the RPMs while having elfutils installed. This allows CMake to strip the binaries when building RPM and debuginfo packages.
=> bug: Not having elfutils resulted in unstripped RPMs for 4.1.2

src/data/featured_projects.json
- Update current star counts for all projects
- Add github.com/teoseller/osquery-attck
- Remove github.com/OktaSecurityLabs/sgt (no longer top 9 by stars)
=> Update featured projects and include teoseller/osquery-attck

tools/new_release.sh
This is a basic script that uses the `osquery` repo and tooling to generate the metadata and schema for a new release for the website.
=> Add script to create new release JSON

src/data/pages/downloads.json
Replaced 'brew' installation method with 'brew cask' as per #172
=> Replaced 'brew' installation method

src/index.scss
In the schema page we block the scroll of the main area
when we hover on the table list sidebar by hiding the scrollbars
with "overflow: hidden".
This though causes an update to the layout and everything moves
to the right when hovering the sidebar and to the left when not.
Instead of causing a layout change, we keep the scrollbars visible,
but we "disable" scrolling via "position: fixed".
=> Schema page: block scroll on sidebar hover without hiding

src/data/blog/posts/official_news/2020-09-10-linux-arm64-beta-support.md, src/pages/BlogShow/BlogShow.js, src/pages/BlogShow/BlogShow.scss, src/pages/Downloads/Downloads.js, src/pages/Downloads/Downloads.scss
Heads up that the download locations and hashes are placeholders. When there is a real 4.5.0 tag and when real packages are built I will upload and update the data here.
@alessandrogario please review and let me know if you have suggestions.
=> blog: Add aarch64 beta post

src/data/community_events/manifest.js, src/data/community_events/osquery@scale2021.json
Historically this medium has been understandably reserved for live events. Given the climate of live events, I thought it would be appropriate to make this request.
=> Updating "Upcoming Community Events" with osquery@scale 2021

src/data/pages/downloads.json
Update `brew install` instructions to:
1. Remove `brew update` (it's auto-updating so not required)
2. Change `brew cask install osquery` to `brew install --cask osquery` as per the new method.
=> Update `brew install` instructions

src/data/osquery_package_versions/4.6.0.json
See https://github.com/osquery/osquery/issues/6837 for the context. We changed a build configuration option to rebuild the 4.6.0 release without dynamic runtime linking.
=> Update windows to 4.6.0.2 revision

src/data/featured_projects.json
Replace Doorman (no commits for last two years) and
kolide/fleet (officially archived) with osctrl and Fleet.
=> Update featured projects

src/data/pages/downloads.json
It looks like the file https://pkg.osquery.io/rpm/osquery-s3-rpm.repo names the repo `osquery-s3-rpm-repo`.
=> Fix YUM repo install instructions

.github/workflows/ci.yml, src/components/Footer/Footer.js
I inadvertently committed something that, while syntactically correct, fails linting and this breaks builds. So now I'm adding a CI job to catch this sooner. (I can't add a `yarn build` to ci, because our build has warnings, and CI triggers fail on them)
Also, fixing the linting error.
=> Fix lint error (And add ci linting)

.github/workflows/ci.yml, config/webpack.config.prod.js, package.json, src/components/App/App.test.js, yarn.lock
After merging the dependabot PRs, something broke. And in my local checkout, something feels very flakey. So I'm taking a somewhat deeper look at ci and the build...
1. Add missing dependency, inadvertently created from a dependabot update
2. Add more CI for building & testing
3. pin the node version to 12
4. Some updates to webpack to support splitting into a couple chunks (should be slightly more cachable)
5. ci should fail if yarn modifies anything
=> Missing dependency and more CI

src/data/osquery_package_versions/4.9.0.json
Heads up @directionless and @muffins, we need to coordinate re-running GH workflows after a release. When the S3 and tag assets are updated, the hash on the website needs to be updated too. It's best to only run those workflows once.
=> Update Windows 4.9.0 hash after GH workflow was rerun

src/components/Footer/Footer.js
Sadly, the Fastly sponsorship didn't work out. As such, remove them from the list
=> Remove Fastly from the sponsors list

src/pages/Downloads/Downloads.js, src/pages/Downloads/Downloads.scss
This makes copy/pasting the terminal commands much better. The whole
block can be copied at once without syntax errors that previously
occurred due to copying the `$` characters.
Tested on macOS Chrome and Firefox.
=> Make terminal prompt unselectable in install commands

src/components/SchemaTOC/SchemaTOC.js, src/components/SchemaTOC/SchemaTOC.scss, src/index.scss
toggle 'noscroll' style on body will cause #49 issue in some browsers
this pr instead use `overscroll-behavior: none` to prevent over scrolling on side list that causing scrolling chain
=> Fix schema page visual jumping #49

.github/workflows/release.yml
This roughs in running the website release in GitHub Actions.
It's not totally clear what kind of permissions need to be in place. Maybe this will work
=> Rough in GHA workflow to generate website builds

src/data/pages/downloads.json, src/pages/Downloads/Downloads.js
I'm not convinced I love this, but it's the best I can do with the framework here...
We have two things we need to change in the alternate downloads.
First, we don't mention windows arm. This feels a little awkward -- we don't have an MSI, so it feels weird to add a tile for it. So I added it to the alternates below. (Fixes #284)
Second, people on older ubuntu/debian machines, need the older dpkg instructions -- the ones based on `apt-key`. (Relates to #275)
I spent some time tinkering with this code. And thought the simplest thing would be to replace the `subSection1Heading` and `subSection1Paragraph1` with an array of heading/paragraph/terminal objects. I don't love the rendering, but I'm not sure it's _worse_...
=> Update the downloads page to include more alternates
